START TRANSACTION;

ALTER DATABASE `reindeer` CHARACTER SET utf8;

ALTER TABLE `addresses` CHARACTER SET utf8;
ALTER TABLE `comments` CHARACTER SET utf8;
ALTER TABLE `credit_note_numbers` CHARACTER SET utf8;
ALTER TABLE `customers` CHARACTER SET utf8;
ALTER TABLE `files` CHARACTER SET utf8;
ALTER TABLE `invoice_numbers` CHARACTER SET utf8;
ALTER TABLE `items` CHARACTER SET utf8;
ALTER TABLE `jobs_states` CHARACTER SET utf8;
ALTER TABLE `orders` CHARACTER SET utf8;
ALTER TABLE `transactions` CHARACTER SET utf8;
ALTER TABLE `users` CHARACTER SET utf8;

COMMIT;